# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
cache: pip
sudo: false

matrix:
  include:
    - env: TOXENV=py34-dj111-wt2
      python: 3.4
    - env: TOXENV=py35-dj111-wt2
      python: 3.5
    - env: TOXENV=py36-dj111-wt2
      python: 3.6
    - env: TOXENV=py37-dj111-wt2
      python: 3.7
    - env: TOXENV=py37-dj2-wt21
      python: 3.7
    - env: TOXENV=py37-dj2-wt22
      python: 3.7
    - env: TOXENV=py37-dj2-wt23
      python: 3.7
    - env: TOXENV=py37-dj2-wt24
      python: 3.7
    - env: TOXENV=py37-dj21-wt24
      python: 3.7
    - env: TOXENV=py37-dj22-wt25
      python: 3.7
    - env: TOXENV=py37-dj22-wt26
      python: 3.7
    - env: TOXENV=py38-dj22-wt27
      python: 3.8
    - env: TOXENV=py38-dj3-wt28
      python: 3.8
    - env: TOXENV=py38-dj3-wt29
      python: 3.8

install:
  - pip install tox

script:
  - tox
